// actionTypes.js
export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';
// analysisActionTypes.js
export const FETCH_ANALYSIS_REQUEST = 'FETCH_ANALYSIS_REQUEST';
export const FETCH_ANALYSIS_SUCCESS = 'FETCH_ANALYSIS_SUCCESS';
export const FETCH_ANALYSIS_FAILURE = 'FETCH_ANALYSIS_FAILURE';
// subscriptionTypes.js
export const FETCH_SUBSCRIPTION_REQUEST = 'FETCH_SUBSCRIPTION_REQUEST';
export const FETCH_SUBSCRIPTION_SUCCESS = 'FETCH_SUBSCRIPTION_SUCCESS';
export const FETCH_SUBSCRIPTION_FAILURE = 'FETCH_SUBSCRIPTION_FAILURE';
// getuserdataAction.js
export const GET_USER_DATA_REQUEST = 'GET_USER_DATA_REQUEST';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILURE = 'GET_USER_DATA_FAILURE';
// updateBookmark.js
export const UPDATE_BOOKMARK_REQUEST = 'UPDATE_BOOKMARK_REQUEST';
export const UPDATE_BOOKMARK_SUCCESS = 'UPDATE_BOOKMARK_SUCCESS';
export const UPDATE_BOOKMARK_FAILURE = 'UPDATE_BOOKMARK_FAILURE';
// getBookmark.js
export const GET_BOOKMARK_DATA_REQUEST = 'GET_BOOKMARK_DATA_REQUEST';
export const GET_BOOKMARK_DATA_SUCCESS = 'GET_BOOKMARK_DATA_SUCCESS';
export const GET_BOOKMARK_DATA_FAILURE = 'GET_BOOKMARK_DATA_FAILURE';
export const CLEAR_BOOKMARK_DATA = 'CLEAR_BOOKMARK_DATA';
// getActivity
export const GET_ACTIVITY_DATA_REQUEST = 'GET_ACTIVITY_DATA_REQUEST';
export const GET_ACTIVITY_DATA_SUCCESS = 'GET_ACTIVITY_DATA_SUCCESS';
export const GET_ACTIVITY_DATA_FAILURE = 'GET_ACTIVITY_DATA_FAILURE';
export const CLEAR_ACTIVITY_DATA = 'CLEAR_ACTIVITY_DATA';
// postNewsLetterSetting
export const UPDATE_NEWSLETTER = 'UPDATE_NEWSLETTER';
export const UPDATE_NEWSLETTER_SUCCESS = 'UPDATE_NEWSLETTER_SUCCESS';
export const UPDATE_NEWSLETTER_FAILURE = 'UPDATE_NEWSLETTER_FAILURE';
// updateNotification
export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION';
export const UPDATE_NOTIFICATION_SUCCESS = 'UPDATE_NOTIFICATION_SUCCESS';
export const UPDATE_NOTIFICATION_FAILURE = 'UPDATE_NOTIFICATION_FAILURE';
// updateProfileAction
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
export const CLEAR_PROFILE_STATUS = 'CLEAR_PROFILE_STATUS';
// actionTypes.js
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';
// logout
export const LOGOUT = 'LOGOUT';
// update subscription
export const UPDATE_SUBSCRIPTION_REQUEST = 'UPDATE_SUBSCRIPTION_REQUEST';
export const UPDATE_SUBSCRIPTION_SUCCESS = 'UPDATE_SUBSCRIPTION_SUCCESS';
export const UPDATE_SUBSCRIPTION_ERROR = 'UPDATE_SUBSCRIPTION_ERROR';
